@startuml
skinparam classAttributeIconSize 0
abstract class Shape{
    - width: float
    - height: float
    + getWidth(): float
    + getHeight(): float
    + setWidth(): void
    + setHeight(): void
    + {abstract} calculateArea(): float
}
class Rectangle
class Triangle
Rectangle --|> Shape
Triangle --|> Shape
@enduml